In [1]:
import numpy as np
import pandas as pd
from models import Pipeline,Hankel
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

2023-04-27 18:41:47.573363: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-27 18:41:47.613694: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-27 18:41:47.614808: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-27 18:41:48.466306: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
df1 = pd.read_csv('~/data/ctown/dataset03.csv')
df2 = pd.read_csv('~/data/ctown/dataset04.csv')
df = pd.concat((df1,df2),axis=0,ignore_index=True)
df_test = pd.read_csv('~/data/ctown/test_dataset.csv')

In [3]:
df_test.columns

Index(['DATETIME', 'L_T1', 'L_T2', 'L_T3', 'L_T4', 'L_T5', 'L_T6', 'L_T7',
       'F_PU1', 'S_PU1', 'F_PU2', 'S_PU2', 'F_PU3', 'S_PU3', 'F_PU4', 'S_PU4',
       'F_PU5', 'S_PU5', 'F_PU6', 'S_PU6', 'F_PU7', 'S_PU7', 'F_PU8', 'S_PU8',
       'F_PU9', 'S_PU9', 'F_PU10', 'S_PU10', 'F_PU11', 'S_PU11', 'F_V2',
       'S_V2', 'P_J280', 'P_J269', 'P_J300', 'P_J256', 'P_J289', 'P_J415',
       'P_J302', 'P_J306', 'P_J307', 'P_J317', 'P_J14', 'P_J422', 'ATT_FLAG'],
      dtype='object')

In [4]:
def fun(X_train,Y_train,X_test,Y_test):
    rf = RandomForestClassifier()
    rf.fit(X_train,Y_train) 
    Y_pred = rf.predict(X_test)
    print('Accuracy:', accuracy_score(Y_test, Y_pred))
    print('Precision: ',precision_score(Y_test,Y_pred))
    print('Recall: ',recall_score(Y_test,Y_pred))
    print('Fscore: ',f1_score(Y_test,Y_pred))

In [5]:
X_train = df[['S_PU3','F_PU3']]
Y_train = df['ATT_FLAG']
X_test = df_test[['S_PU3','F_PU3']]
Y_test = df_test['ATT_FLAG']
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8051699377692676
Precision:  0.0
Recall:  0.0
Fscore:  0.0


In [6]:
X_train = df[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','P_J269']]
X_test = df_test[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','P_J269']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8056486357108664
Precision:  0.5098039215686274
Recall:  0.06388206388206388
Fscore:  0.11353711790393015


In [7]:
X_train = df[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','S_PU3','F_PU3','P_J269']]
X_test = df_test[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','S_PU3','F_PU3','P_J269']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8032551460028722
Precision:  0.4523809523809524
Recall:  0.04668304668304668
Fscore:  0.08463251670378619


In [8]:
X_train = df[['L_T3','S_PU4','F_PU4','S_PU5','F_PU5']]
X_test = df_test[['L_T3','S_PU4','F_PU4','S_PU5','F_PU5']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.7999042604116803
Precision:  0.07692307692307693
Recall:  0.002457002457002457
Fscore:  0.0047619047619047615


In [9]:
X_train = df[['L_T2','S_V2','F_V2','P_J14','P_J422']]
X_test = df_test[['L_T2','S_V2','F_V2','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8113930110100527
Precision:  0.8421052631578947
Recall:  0.03931203931203931
Fscore:  0.07511737089201878


In [10]:
X_train = df[['L_T2','L_T3','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','P_J14','P_J422']]
X_test = df_test[['L_T2','L_T3','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8080421254188607
Precision:  0.6666666666666666
Recall:  0.029484029484029485
Fscore:  0.05647058823529412


In [11]:
X_train = df[['L_T2','L_T3','L_T7','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
X_test = df_test[['L_T2','L_T3','L_T7','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8118717089516515
Precision:  0.9375
Recall:  0.036855036855036855
Fscore:  0.07092198581560283


In [12]:
X_train = df[['L_T1','L_T2','L_T3','L_T7','S_V2','F_V2','S_PU1','F_PU1','S_PU2','F_PU2','S_PU3','F_PU3','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
X_test = df_test[['L_T1','L_T2','L_T3','L_T7','S_V2','F_V2','S_PU1','F_PU1','S_PU2','F_PU2','S_PU3','F_PU3','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8190521780756342
Precision:  0.9393939393939394
Recall:  0.07616707616707617
Fscore:  0.14090909090909093


In [13]:
df[df['ATT_FLAG']==0]['L_T1'].mean()

2.681205666486904

In [14]:
df[df['ATT_FLAG']==1]['L_T1'].mean()

2.8273983739837396

In [15]:
df[df['ATT_FLAG']==0]['L_T2'].mean()

3.2843085281952438

In [16]:
df[df['ATT_FLAG']==1]['L_T2'].mean()

3.3409756097560974

In [17]:
df[df['ATT_FLAG']==0]['L_T3'].mean()

4.202603932783224

In [18]:
df[df['ATT_FLAG']==1]['L_T3'].mean()

4.204715447154471

In [19]:
df[df['ATT_FLAG']==0]['L_T4'].mean()

3.56817108838422

In [20]:
df[df['ATT_FLAG']==1]['L_T4'].mean()

3.4660569105691055

In [21]:
df[df['ATT_FLAG']==0]['L_T5'].mean()

2.748624297430982

In [22]:
df[df['ATT_FLAG']==1]['L_T5'].mean()

2.7390650406504067

In [23]:
df[df['ATT_FLAG']==0]['L_T6'].mean()

5.370080021028442

In [24]:
df[df['ATT_FLAG']==1]['L_T6'].mean()

5.362418699186992

In [25]:
df[df['ATT_FLAG']==0]['L_T7'].mean()

3.309937061904628

In [26]:
df[df['ATT_FLAG']==1]['L_T7'].mean()

3.294451219512195

In [27]:
df_test[df_test['ATT_FLAG']==0]['L_T1'].mean()

2.715677764565993

In [28]:
df_test[df_test['ATT_FLAG']==1]['L_T1'].mean()

3.042997542997543

In [29]:
df_test[df_test['ATT_FLAG']==0]['L_T2'].mean()

3.340481569560048

In [30]:
df_test[df_test['ATT_FLAG']==1]['L_T2'].mean()

3.4082063882063887

In [31]:
df_test[df_test['ATT_FLAG']==0]['L_T3'].mean()

4.198382877526754

In [32]:
df_test[df_test['ATT_FLAG']==1]['L_T3'].mean()

4.201179361179362

In [33]:
df_test[df_test['ATT_FLAG']==0]['L_T4'].mean()

3.571956004756242

In [34]:
df_test[df_test['ATT_FLAG']==1]['L_T4'].mean()

3.563808353808354

In [35]:
df_test[df_test['ATT_FLAG']==0]['L_T5'].mean()

2.754643281807372

In [36]:
df_test[df_test['ATT_FLAG']==1]['L_T5'].mean()

2.7463144963144965

In [37]:
df_test[df_test['ATT_FLAG']==0]['L_T6'].mean()

5.371456599286564

In [38]:
df_test[df_test['ATT_FLAG']==1]['L_T6'].mean()

5.388820638820639

In [39]:
df_test[df_test['ATT_FLAG']==0]['L_T7'].mean()

3.2840071343638524

In [40]:
df_test[df_test['ATT_FLAG']==1]['L_T7'].mean()

3.3401965601965604

In [46]:
model = tf.keras.Sequential([
  layers.Dense(64, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(2, activation='softmax')
])

In [47]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='categorical_crossentropy',
              metrics=['f1_score'])

In [48]:
X_train = df.drop(columns=['DATETIME','ATT_FLAG'])
Y_train = df['ATT_FLAG']
X_test = df_test.drop(columns=['DATETIME','ATT_FLAG'])
Y_test = df_test['ATT_FLAG']

In [49]:
Y_train = tf.keras.utils.to_categorical(Y_train)
Y_test = tf.keras.utils.to_categorical(Y_test)

In [50]:
model.fit(X_train, Y_train, epochs=5, batch_size=64)

Epoch 1/5


ValueError: in user code:

    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1055, in train_step
        return self.compute_metrics(x, y, y_pred, sample_weight)
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1149, in compute_metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 577, in update_state
        self.build(y_pred, y_true)
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 483, in build
        self._metrics = tf.__internal__.nest.map_structure_up_to(
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 631, in _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 631, in <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    File "/home/manu/.local/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 650, in _get_metric_object
        metric_obj = metrics_mod.get(metric)
    File "/home/manu/.local/lib/python3.10/site-packages/keras/metrics/__init__.py", line 204, in get
        return deserialize(str(identifier))
    File "/home/manu/.local/lib/python3.10/site-packages/keras/metrics/__init__.py", line 158, in deserialize
        return deserialize_keras_object(
    File "/home/manu/.local/lib/python3.10/site-packages/keras/saving/legacy/serialization.py", line 543, in deserialize_keras_object
        raise ValueError(

    ValueError: Unknown metric function: 'f1_score'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.


In [65]:
def f1(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.round(y_pred)
    return f1_score(y_true, y_pred, average='weighted')

# Register the custom metric function with Keras
tf.keras.utils.get_custom_objects()['f1'] = f1

model = tf.keras.Sequential([
  layers.Dense(64, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

X_train = df.drop(columns=['DATETIME','ATT_FLAG'])
Y_train = df['ATT_FLAG']
X_test = df_test.drop(columns=['DATETIME','ATT_FLAG'])
Y_test = df_test['ATT_FLAG']

model.fit(X_train, Y_train, epochs=10, batch_size=64, validation_data=(X_test, Y_test))


Epoch 1/10
203/203 [==============================] - 1s 2ms/step - loss: 1.3852 - accuracy: 0.9285 - val_loss: 0.8207 - val_accuracy: 0.8186
Epoch 2/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1423 - accuracy: 0.9690 - val_loss: 0.7904 - val_accuracy: 0.8186
Epoch 3/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1429 - accuracy: 0.9697 - val_loss: 0.6607 - val_accuracy: 0.8191
Epoch 4/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1448 - accuracy: 0.9699 - val_loss: 0.7383 - val_accuracy: 0.8195
Epoch 5/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1354 - accuracy: 0.9702 - val_loss: 0.7151 - val_accuracy: 0.8191
Epoch 6/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1330 - accuracy: 0.9704 - val_loss: 0.5677 - val_accuracy: 0.8219
Epoch 7/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1325 - accuracy: 0.9706 - val_loss: 0.6748 - val_accuracy: 0.8229
Epoch 

In [66]:
Y_pred = model.predict(X_test)

66/66 [==============================] - 0s 751us/step


In [67]:
Y_pred = np.round(Y_pred)
print('Accuracy:', accuracy_score(Y_test, Y_pred))
print('Precision: ',precision_score(Y_test,Y_pred))
print('Recall: ',recall_score(Y_test,Y_pred))
print('Fscore: ',f1_score(Y_test,Y_pred))

Accuracy: 0.8247965533748205
Precision:  1.0
Recall:  0.10073710073710074
Fscore:  0.18303571428571427


In [108]:
X = X_train.iloc[:,0].values
centroid_old = X[np.random.choice(range(len(X)), 3)]
centroid_old

array([4.49063349, 3.84247041, 0.71590203])

In [110]:
distances = np.sqrt(((X - centroid_old[:, np.newaxis])**2))
distances

array([[3.98090357, 4.078053  , 4.17052165, ..., 2.58063349, 2.97063349,
        3.39063349],
       [3.33274048, 3.42988992, 3.52235857, ..., 1.93247041, 2.32247041,
        2.74247041],
       [0.20617211, 0.30332154, 0.39579019, ..., 1.19409797, 0.80409797,
        0.38409797]])

In [114]:
np.argsort(np.min(distances,axis=0))

array([ 4573,  2137,  8707, ..., 11239, 11824,  1053])

In [122]:
np.min(distances,axis=0)[11239]

1.5624704070000002

In [111]:
np.sqrt(((X - centroid_old[0])**2))

array([3.98090357, 4.078053  , 4.17052165, ..., 2.58063349, 2.97063349,
       3.39063349])

In [ ]:
labels = np.argmin(distances, axis=0)
labels

In [86]:
len(np.sqrt(((X - centroid_old[1])**2)))

12938

In [85]:
len(X)

12938

In [105]:
centroid_old = X[np.random.choice(range(len(X)), 4)]
distances = np.sqrt(((X - centroid_old[:, np.newaxis])**2).sum(axis=1))
distances


array([154.12324614, 230.3096215 , 198.08671738, 248.92622271])

In [106]:
labels = np.argmin(distances, axis=0)
labels

0

In [107]:
X.shape

(12938,)