In [20]:
import numpy as np
import pandas as pd
from models import Pipeline,Hankel,Robustcluster,RobustPCA,Rank
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

In [21]:
from scipy.linalg import svd

In [22]:
df1 = pd.read_csv('~/data/ctown/dataset03.csv')
df2 = pd.read_csv('~/data/ctown/dataset04.csv')
df = pd.concat((df1,df2),axis=0,ignore_index=True)
df_test = pd.read_csv('~/data/ctown/test_dataset.csv')

In [23]:
hankel = Hankel()
pca=RobustPCA()
rank=Rank()


In [24]:
rc = Robustcluster()

In [25]:
df.loc[:,'S_PU3'].values

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
sensors = [col for col in df.columns if col not in ['DATETIME','ATT_FLAG']]

In [27]:
len(sensors)

43

In [28]:
sensors

['L_T1',
 'L_T2',
 'L_T3',
 'L_T4',
 'L_T5',
 'L_T6',
 'L_T7',
 'F_PU1',
 'S_PU1',
 'F_PU2',
 'S_PU2',
 'F_PU3',
 'S_PU3',
 'F_PU4',
 'S_PU4',
 'F_PU5',
 'S_PU5',
 'F_PU6',
 'S_PU6',
 'F_PU7',
 'S_PU7',
 'F_PU8',
 'S_PU8',
 'F_PU9',
 'S_PU9',
 'F_PU10',
 'S_PU10',
 'F_PU11',
 'S_PU11',
 'F_V2',
 'S_V2',
 'P_J280',
 'P_J269',
 'P_J300',
 'P_J256',
 'P_J289',
 'P_J415',
 'P_J302',
 'P_J306',
 'P_J307',
 'P_J317',
 'P_J14',
 'P_J422']

'F_PU6', 'F_PU5'

In [29]:
XX=df.loc[:,'F_PU5'].values
XX = hankel.fit(XX,lag=60)
XX = XX.T
print(XX)
r=rank.fit(XX)
print(r)
print("rank",r)
V=pca.fit(XX,r,0.05)
print("2")
print(V)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
59
rank 59
pca iteration- 0
2
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [32]:
for sens in ['S_PU4']:
  XX=df.loc[:,sens].values
  XX = hankel.fit(XX,lag=60)
  XX = XX.T 
  r=rank.fit(XX)
  print("rank",r)
  V=pca.fit(XX,r,0.05)
  print(V)

rank 16
pca iteration- 0
pca iteration- 1
[[-1.60245393e-01 -1.65135926e-01 -1.62906665e-01 ... -9.42401104e-02
  -8.77623727e-02 -1.33383105e-01]
 [-1.40556246e-01 -1.47071356e-01 -1.44993046e-01 ...  1.14329655e-01
   4.00264969e-03 -9.62685826e-02]
 [ 2.92485069e-02 -1.39101949e-02 -2.07686086e-02 ...  2.09562524e-01
   2.40054388e-01  1.36860471e-01]
 ...
 [ 0.00000000e+00  1.61338821e-03  2.29254549e-16 ... -8.32667268e-17
  -1.24900090e-16  1.11022302e-16]
 [ 0.00000000e+00 -1.15913423e-03  3.12385751e-16 ...  2.22044605e-16
  -2.49800181e-16 -1.11022302e-16]
 [ 0.00000000e+00  7.50647593e-17  1.12563983e-16 ...  9.10761959e-17
  -1.89120128e-17  1.69274707e-17]]


In [ ]:
U,sig,V=svd(X_train)

In [ ]:
V

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:
df_test.columns

Index(['DATETIME', 'L_T1', 'L_T2', 'L_T3', 'L_T4', 'L_T5', 'L_T6', 'L_T7',
       'F_PU1', 'S_PU1', 'F_PU2', 'S_PU2', 'F_PU3', 'S_PU3', 'F_PU4', 'S_PU4',
       'F_PU5', 'S_PU5', 'F_PU6', 'S_PU6', 'F_PU7', 'S_PU7', 'F_PU8', 'S_PU8',
       'F_PU9', 'S_PU9', 'F_PU10', 'S_PU10', 'F_PU11', 'S_PU11', 'F_V2',
       'S_V2', 'P_J280', 'P_J269', 'P_J300', 'P_J256', 'P_J289', 'P_J415',
       'P_J302', 'P_J306', 'P_J307', 'P_J317', 'P_J14', 'P_J422', 'ATT_FLAG'],
      dtype='object')

In [ ]:
def fun(X_train,Y_train,X_test,Y_test):
    rf = RandomForestClassifier()
    rf.fit(X_train,Y_train) 
    Y_pred = rf.predict(X_test)
    print('Accuracy:', accuracy_score(Y_test, Y_pred))
    print('Precision: ',precision_score(Y_test,Y_pred))
    print('Recall: ',recall_score(Y_test,Y_pred))
    print('Fscore: ',f1_score(Y_test,Y_pred))

In [ ]:
X_train = df[['S_PU3','F_PU3']]
Y_train = df['ATT_FLAG']
X_test = df_test[['S_PU3','F_PU3']]
Y_test = df_test['ATT_FLAG']
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8051699377692676
Precision:  0.0
Recall:  0.0
Fscore:  0.0


In [ ]:
X_train = df[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','P_J269']]
X_test = df_test[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','P_J269']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8051699377692676
Precision:  0.5
Recall:  0.056511056511056514
Fscore:  0.10154525386313466


In [ ]:
X_train = df[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','S_PU3','F_PU3','P_J269']]
X_test = df_test[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','S_PU3','F_PU3','P_J269']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.7989468645284825
Precision:  0.32432432432432434
Recall:  0.029484029484029485
Fscore:  0.05405405405405405


In [ ]:
X_train = df[['L_T3','S_PU4','F_PU4','S_PU5','F_PU5']]
X_test = df_test[['L_T3','S_PU4','F_PU4','S_PU5','F_PU5']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8003829583532791
Precision:  0.08333333333333333
Recall:  0.002457002457002457
Fscore:  0.0047732696897374695


In [ ]:
X_train = df[['L_T2','S_V2','F_V2','P_J14','P_J422']]
X_test = df_test[['L_T2','S_V2','F_V2','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8080421254188607
Precision:  0.6363636363636364
Recall:  0.0343980343980344
Fscore:  0.06526806526806528


In [ ]:
X_train = df[['L_T2','L_T3','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','P_J14','P_J422']]
X_test = df_test[['L_T2','L_T3','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8066060315940642
Precision:  0.5882352941176471
Recall:  0.02457002457002457
Fscore:  0.04716981132075472


In [ ]:
X_train = df[['L_T2','L_T3','L_T7','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
X_test = df_test[['L_T2','L_T3','L_T7','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8104356151268549
Precision:  0.8666666666666667
Recall:  0.03194103194103194
Fscore:  0.06161137440758294


In [ ]:
X_train = df[['L_T1','L_T2','L_T3','L_T7','S_V2','F_V2','S_PU1','F_PU1','S_PU2','F_PU2','S_PU3','F_PU3','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
X_test = df_test[['L_T1','L_T2','L_T3','L_T7','S_V2','F_V2','S_PU1','F_PU1','S_PU2','F_PU2','S_PU3','F_PU3','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8190521780756342
Precision:  1.0
Recall:  0.07125307125307126
Fscore:  0.13302752293577982


In [ ]:
df[df['ATT_FLAG']==0]['L_T1'].mean()

2.681205666486904

In [ ]:
df[df['ATT_FLAG']==1]['L_T1'].mean()

2.8273983739837396

In [ ]:
df[df['ATT_FLAG']==0]['L_T2'].mean()

3.2843085281952438

In [ ]:
df[df['ATT_FLAG']==1]['L_T2'].mean()

3.3409756097560974

In [ ]:
df[df['ATT_FLAG']==0]['L_T3'].mean()

4.202603932783224

In [ ]:
df[df['ATT_FLAG']==1]['L_T3'].mean()

4.204715447154471

In [ ]:
df[df['ATT_FLAG']==0]['L_T4'].mean()

3.56817108838422

In [ ]:
df[df['ATT_FLAG']==1]['L_T4'].mean()

3.4660569105691055

In [ ]:
df[df['ATT_FLAG']==0]['L_T5'].mean()

2.748624297430982

In [ ]:
df[df['ATT_FLAG']==1]['L_T5'].mean()

2.7390650406504067

In [ ]:
df[df['ATT_FLAG']==0]['L_T6'].mean()

5.370080021028442

In [ ]:
df[df['ATT_FLAG']==1]['L_T6'].mean()

5.362418699186992

In [ ]:
df[df['ATT_FLAG']==0]['L_T7'].mean()

3.309937061904628

In [ ]:
df[df['ATT_FLAG']==1]['L_T7'].mean()

3.294451219512195

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T1'].mean()

2.715677764565993

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T1'].mean()

3.042997542997543

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T2'].mean()

3.340481569560048

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T2'].mean()

3.4082063882063887

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T3'].mean()

4.198382877526754

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T3'].mean()

4.201179361179362

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T4'].mean()

3.571956004756242

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T4'].mean()

3.563808353808354

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T5'].mean()

2.754643281807372

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T5'].mean()

2.7463144963144965

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T6'].mean()

5.371456599286564

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T6'].mean()

5.388820638820639

In [ ]:
df_test[df_test['ATT_FLAG']==0]['L_T7'].mean()

3.2840071343638524

In [ ]:
df_test[df_test['ATT_FLAG']==1]['L_T7'].mean()

3.3401965601965604

In [ ]:
model = tf.keras.Sequential([
  layers.Dense(64, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(2, activation='softmax')
])

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
X_train = df.drop(columns=['DATETIME','ATT_FLAG'])
Y_train = df['ATT_FLAG']
X_test = df_test.drop(columns=['DATETIME','ATT_FLAG'])
Y_test = df_test['ATT_FLAG']

In [ ]:
Y_train = tf.keras.utils.to_categorical(Y_train)
Y_test = tf.keras.utils.to_categorical(Y_test)

In [ ]:
model.fit(X_train, Y_train, epochs=5, batch_size=64)

Epoch 1/5
203/203 [==============================] - 5s 5ms/step - loss: 0.2044 - accuracy: 0.9635
Epoch 2/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1600 - accuracy: 0.9683
Epoch 3/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1477 - accuracy: 0.9699
Epoch 4/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1417 - accuracy: 0.9703
Epoch 5/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1363 - accuracy: 0.9709


In [ ]:
def f1(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.round(y_pred)
    return f1_score(y_true, y_pred, average='weighted')

# Register the custom metric function with Keras
tf.keras.utils.get_custom_objects()['f1'] = f1

model = tf.keras.Sequential([
  layers.Dense(64, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

X_train = df.drop(columns=['DATETIME','ATT_FLAG'])
Y_train = df['ATT_FLAG']
X_test = df_test.drop(columns=['DATETIME','ATT_FLAG'])
Y_test = df_test['ATT_FLAG']

model.fit(X_train, Y_train, epochs=10, batch_size=64, validation_data=(X_test, Y_test))


Epoch 1/10
203/203 [==============================] - 3s 7ms/step - loss: 0.1687 - accuracy: 0.9658 - val_loss: 0.6507 - val_accuracy: 0.8009
Epoch 2/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1472 - accuracy: 0.9695 - val_loss: 0.6339 - val_accuracy: 0.8066
Epoch 3/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1496 - accuracy: 0.9696 - val_loss: 0.6946 - val_accuracy: 0.8047
Epoch 4/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1430 - accuracy: 0.9699 - val_loss: 0.7909 - val_accuracy: 0.8056
Epoch 5/10
203/203 [==============================] - ETA: 0s - loss: 0.1419 - accuracy: 0.96 - 0s 1ms/step - loss: 0.1406 - accuracy: 0.9702 - val_loss: 0.8831 - val_accuracy: 0.8056
Epoch 6/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1351 - accuracy: 0.9709 - val_loss: 0.6483 - val_accuracy: 0.8061
Epoch 7/10
203/203 [==============================] - ETA: 0s - loss: 0.1539 - accuracy: 0.96 - 0s 1ms/ste

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
Y_pred = np.round(Y_pred)
print('Accuracy:', accuracy_score(Y_test, Y_pred))
print('Precision: ',precision_score(Y_test,Y_pred))
print('Recall: ',recall_score(Y_test,Y_pred))
print('Fscore: ',f1_score(Y_test,Y_pred))

Accuracy: 0.8089995213020584
Precision:  1.0
Recall:  0.019656019656019656
Fscore:  0.03855421686746988


In [ ]:
X = X_train.iloc[:,0].values
centroid_old = X[np.random.choice(range(len(X)), 3)]
centroid_old

array([2.26569486, 0.86      , 3.73      ])

In [ ]:
distances = np.sqrt(((X - centroid_old[:, np.newaxis])**2))
distances

array([[1.75596494, 1.85311437, 1.94558302, ..., 0.35569486, 0.74569486,
        1.16569486],
       [0.35027008, 0.44741951, 0.53988816, ..., 1.05      , 0.66      ,
        0.24      ],
       [3.22027008, 3.31741951, 3.40988816, ..., 1.82      , 2.21      ,
        2.63      ]])

In [ ]:
np.argsort(np.min(distances,axis=0))

array([12825,  9966,  9570, ..., 11124, 11103, 11104], dtype=int64)

In [ ]:
X[np.argsort(np.min(distances,axis=0))][:-round(.039*len(X))]

array([3.73, 3.73, 3.73, ..., 4.47, 4.47, 4.47])

In [ ]:
idx = np.argsort(np.min(distances,axis=0))
idx

array([12825,  9966,  9570, ..., 11124, 11103, 11104], dtype=int64)

In [ ]:
temp = X[idx[:-round(.039*len(X))]]
temp

array([3.73, 3.73, 3.73, ..., 4.47, 4.47, 4.47])

In [ ]:
labels = np.argmin(distances,axis=0)[idx[:-round(.039*len(X))]]

In [ ]:
np.mean(temp[labels == 2])

3.7576338527722197

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.argmin(distances,axis=0)[:round(.039*len(X))]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
round(.039*len(X))

505

In [ ]:
np.sqrt(((X - centroid_old[0])**2))

: 

In [ ]:
labels = np.argmin(distances, axis=0)
labels

: 

In [ ]:
len(np.sqrt(((X - centroid_old[1])**2)))

: 

In [ ]:
len(X)

: 

In [ ]:
centroid_old = X[np.random.choice(range(len(X)), 4)]
distances = np.sqrt(((X - centroid_old[:, np.newaxis])**2).sum(axis=1))
distances


: 

In [ ]:
labels = np.argmin(distances, axis=0)
labels

: 

In [ ]:
X.shape

: 

: 