In [1]:
import numpy as np
import pandas as pd
from models import Pipeline,Hankel,Robustcluster
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df1 = pd.read_csv('~/data/ctown/dataset03.csv')
df2 = pd.read_csv('~/data/ctown/dataset04.csv')
df = pd.concat((df1,df2),axis=0,ignore_index=True)
df_test = pd.read_csv('~/data/ctown/test_dataset.csv')

In [3]:
hankel = Hankel()

In [4]:
rc = Robustcluster()

In [5]:
X_train = df.iloc[:,1].values
X_train = hankel.fit(X_train,lag=60)
X_train = X_train.T
centre,label = rc.fit(X_train,3,.04)

[[3.36558512 3.42269625 3.46236214 3.48702721 3.50598137 3.52631154
  3.56445123 3.59523499 3.62272629 3.59477496 3.54197885 3.49145292
  3.44969609 3.3984219  3.3088923  3.16781702 2.9762093  2.79282766
  2.63332266 2.4805853  2.33268873 2.170742   2.00541803 1.86131158
  1.74165659 1.6444622  1.55952196 1.48368508 1.43363638 1.43351349
  1.47723619 1.55511236 1.63771315 1.72924575 1.83986964 1.95936192
  2.08045582 2.20819496 2.31922499 2.41314157 2.48458888 2.55163891
  2.64531965 2.76262198 2.88026135 2.97535354 3.0758568  3.17857768
  3.27248427 3.37719246 3.47792813 3.53470605 3.54737852 3.57980956
  3.60557982 3.6384584  3.65569911 3.59635214 3.51782445 3.4440763 ]
 [2.23294227 2.09720507 1.97013248 1.83502513 1.70970897 1.62085634
  1.56026801 1.52651074 1.50888901 1.50905835 1.53121064 1.59778135
  1.68880341 1.80771128 1.94249485 2.07860702 2.21317289 2.33253086
  2.45086339 2.58030644 2.70255879 2.78983518 2.84957356 2.92366702
  3.00767386 3.09749672 3.18901487 3.25393281 3

In [3]:
df_test.columns

Index(['DATETIME', 'L_T1', 'L_T2', 'L_T3', 'L_T4', 'L_T5', 'L_T6', 'L_T7',
       'F_PU1', 'S_PU1', 'F_PU2', 'S_PU2', 'F_PU3', 'S_PU3', 'F_PU4', 'S_PU4',
       'F_PU5', 'S_PU5', 'F_PU6', 'S_PU6', 'F_PU7', 'S_PU7', 'F_PU8', 'S_PU8',
       'F_PU9', 'S_PU9', 'F_PU10', 'S_PU10', 'F_PU11', 'S_PU11', 'F_V2',
       'S_V2', 'P_J280', 'P_J269', 'P_J300', 'P_J256', 'P_J289', 'P_J415',
       'P_J302', 'P_J306', 'P_J307', 'P_J317', 'P_J14', 'P_J422', 'ATT_FLAG'],
      dtype='object')

In [4]:
def fun(X_train,Y_train,X_test,Y_test):
    rf = RandomForestClassifier()
    rf.fit(X_train,Y_train) 
    Y_pred = rf.predict(X_test)
    print('Accuracy:', accuracy_score(Y_test, Y_pred))
    print('Precision: ',precision_score(Y_test,Y_pred))
    print('Recall: ',recall_score(Y_test,Y_pred))
    print('Fscore: ',f1_score(Y_test,Y_pred))

In [5]:
X_train = df[['S_PU3','F_PU3']]
Y_train = df['ATT_FLAG']
X_test = df_test[['S_PU3','F_PU3']]
Y_test = df_test['ATT_FLAG']
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8051699377692676
Precision:  0.0
Recall:  0.0
Fscore:  0.0


In [6]:
X_train = df[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','P_J269']]
X_test = df_test[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','P_J269']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8051699377692676
Precision:  0.5
Recall:  0.056511056511056514
Fscore:  0.10154525386313466


In [7]:
X_train = df[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','S_PU3','F_PU3','P_J269']]
X_test = df_test[['L_T1','S_PU1','F_PU1', 'S_PU2','F_PU2','S_PU3','F_PU3','P_J269']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.7989468645284825
Precision:  0.32432432432432434
Recall:  0.029484029484029485
Fscore:  0.05405405405405405


In [8]:
X_train = df[['L_T3','S_PU4','F_PU4','S_PU5','F_PU5']]
X_test = df_test[['L_T3','S_PU4','F_PU4','S_PU5','F_PU5']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8003829583532791
Precision:  0.08333333333333333
Recall:  0.002457002457002457
Fscore:  0.0047732696897374695


In [9]:
X_train = df[['L_T2','S_V2','F_V2','P_J14','P_J422']]
X_test = df_test[['L_T2','S_V2','F_V2','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8080421254188607
Precision:  0.6363636363636364
Recall:  0.0343980343980344
Fscore:  0.06526806526806528


In [10]:
X_train = df[['L_T2','L_T3','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','P_J14','P_J422']]
X_test = df_test[['L_T2','L_T3','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8066060315940642
Precision:  0.5882352941176471
Recall:  0.02457002457002457
Fscore:  0.04716981132075472


In [11]:
X_train = df[['L_T2','L_T3','L_T7','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
X_test = df_test[['L_T2','L_T3','L_T7','S_V2','F_V2','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8104356151268549
Precision:  0.8666666666666667
Recall:  0.03194103194103194
Fscore:  0.06161137440758294


In [12]:
X_train = df[['L_T1','L_T2','L_T3','L_T7','S_V2','F_V2','S_PU1','F_PU1','S_PU2','F_PU2','S_PU3','F_PU3','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
X_test = df_test[['L_T1','L_T2','L_T3','L_T7','S_V2','F_V2','S_PU1','F_PU1','S_PU2','F_PU2','S_PU3','F_PU3','S_PU4','F_PU4','S_PU5','F_PU5','S_PU10','F_PU10','S_PU11','F_PU11','P_J14','P_J422']]
fun(X_train,Y_train,X_test,Y_test)

Accuracy: 0.8190521780756342
Precision:  1.0
Recall:  0.07125307125307126
Fscore:  0.13302752293577982


In [13]:
df[df['ATT_FLAG']==0]['L_T1'].mean()

2.681205666486904

In [14]:
df[df['ATT_FLAG']==1]['L_T1'].mean()

2.8273983739837396

In [15]:
df[df['ATT_FLAG']==0]['L_T2'].mean()

3.2843085281952438

In [16]:
df[df['ATT_FLAG']==1]['L_T2'].mean()

3.3409756097560974

In [17]:
df[df['ATT_FLAG']==0]['L_T3'].mean()

4.202603932783224

In [18]:
df[df['ATT_FLAG']==1]['L_T3'].mean()

4.204715447154471

In [19]:
df[df['ATT_FLAG']==0]['L_T4'].mean()

3.56817108838422

In [20]:
df[df['ATT_FLAG']==1]['L_T4'].mean()

3.4660569105691055

In [21]:
df[df['ATT_FLAG']==0]['L_T5'].mean()

2.748624297430982

In [22]:
df[df['ATT_FLAG']==1]['L_T5'].mean()

2.7390650406504067

In [23]:
df[df['ATT_FLAG']==0]['L_T6'].mean()

5.370080021028442

In [24]:
df[df['ATT_FLAG']==1]['L_T6'].mean()

5.362418699186992

In [25]:
df[df['ATT_FLAG']==0]['L_T7'].mean()

3.309937061904628

In [26]:
df[df['ATT_FLAG']==1]['L_T7'].mean()

3.294451219512195

In [27]:
df_test[df_test['ATT_FLAG']==0]['L_T1'].mean()

2.715677764565993

In [28]:
df_test[df_test['ATT_FLAG']==1]['L_T1'].mean()

3.042997542997543

In [29]:
df_test[df_test['ATT_FLAG']==0]['L_T2'].mean()

3.340481569560048

In [30]:
df_test[df_test['ATT_FLAG']==1]['L_T2'].mean()

3.4082063882063887

In [31]:
df_test[df_test['ATT_FLAG']==0]['L_T3'].mean()

4.198382877526754

In [32]:
df_test[df_test['ATT_FLAG']==1]['L_T3'].mean()

4.201179361179362

In [33]:
df_test[df_test['ATT_FLAG']==0]['L_T4'].mean()

3.571956004756242

In [34]:
df_test[df_test['ATT_FLAG']==1]['L_T4'].mean()

3.563808353808354

In [35]:
df_test[df_test['ATT_FLAG']==0]['L_T5'].mean()

2.754643281807372

In [36]:
df_test[df_test['ATT_FLAG']==1]['L_T5'].mean()

2.7463144963144965

In [37]:
df_test[df_test['ATT_FLAG']==0]['L_T6'].mean()

5.371456599286564

In [38]:
df_test[df_test['ATT_FLAG']==1]['L_T6'].mean()

5.388820638820639

In [39]:
df_test[df_test['ATT_FLAG']==0]['L_T7'].mean()

3.2840071343638524

In [40]:
df_test[df_test['ATT_FLAG']==1]['L_T7'].mean()

3.3401965601965604

In [41]:
model = tf.keras.Sequential([
  layers.Dense(64, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(2, activation='softmax')
])

In [46]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [47]:
X_train = df.drop(columns=['DATETIME','ATT_FLAG'])
Y_train = df['ATT_FLAG']
X_test = df_test.drop(columns=['DATETIME','ATT_FLAG'])
Y_test = df_test['ATT_FLAG']

In [48]:
Y_train = tf.keras.utils.to_categorical(Y_train)
Y_test = tf.keras.utils.to_categorical(Y_test)

In [49]:
model.fit(X_train, Y_train, epochs=5, batch_size=64)

Epoch 1/5
203/203 [==============================] - 5s 5ms/step - loss: 0.2044 - accuracy: 0.9635
Epoch 2/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1600 - accuracy: 0.9683
Epoch 3/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1477 - accuracy: 0.9699
Epoch 4/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1417 - accuracy: 0.9703
Epoch 5/5
203/203 [==============================] - 1s 4ms/step - loss: 0.1363 - accuracy: 0.9709


In [50]:
def f1(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.round(y_pred)
    return f1_score(y_true, y_pred, average='weighted')

# Register the custom metric function with Keras
tf.keras.utils.get_custom_objects()['f1'] = f1

model = tf.keras.Sequential([
  layers.Dense(64, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

X_train = df.drop(columns=['DATETIME','ATT_FLAG'])
Y_train = df['ATT_FLAG']
X_test = df_test.drop(columns=['DATETIME','ATT_FLAG'])
Y_test = df_test['ATT_FLAG']

model.fit(X_train, Y_train, epochs=10, batch_size=64, validation_data=(X_test, Y_test))


Epoch 1/10
203/203 [==============================] - 3s 7ms/step - loss: 0.1687 - accuracy: 0.9658 - val_loss: 0.6507 - val_accuracy: 0.8009
Epoch 2/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1472 - accuracy: 0.9695 - val_loss: 0.6339 - val_accuracy: 0.8066
Epoch 3/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1496 - accuracy: 0.9696 - val_loss: 0.6946 - val_accuracy: 0.8047
Epoch 4/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1430 - accuracy: 0.9699 - val_loss: 0.7909 - val_accuracy: 0.8056
Epoch 5/10
203/203 [==============================] - ETA: 0s - loss: 0.1419 - accuracy: 0.96 - 0s 1ms/step - loss: 0.1406 - accuracy: 0.9702 - val_loss: 0.8831 - val_accuracy: 0.8056
Epoch 6/10
203/203 [==============================] - 0s 1ms/step - loss: 0.1351 - accuracy: 0.9709 - val_loss: 0.6483 - val_accuracy: 0.8061
Epoch 7/10
203/203 [==============================] - ETA: 0s - loss: 0.1539 - accuracy: 0.96 - 0s 1ms/ste

In [51]:
Y_pred = model.predict(X_test)

In [52]:
Y_pred = np.round(Y_pred)
print('Accuracy:', accuracy_score(Y_test, Y_pred))
print('Precision: ',precision_score(Y_test,Y_pred))
print('Recall: ',recall_score(Y_test,Y_pred))
print('Fscore: ',f1_score(Y_test,Y_pred))

Accuracy: 0.8089995213020584
Precision:  1.0
Recall:  0.019656019656019656
Fscore:  0.03855421686746988


In [53]:
X = X_train.iloc[:,0].values
centroid_old = X[np.random.choice(range(len(X)), 3)]
centroid_old

array([2.26569486, 0.86      , 3.73      ])

In [54]:
distances = np.sqrt(((X - centroid_old[:, np.newaxis])**2))
distances

array([[1.75596494, 1.85311437, 1.94558302, ..., 0.35569486, 0.74569486,
        1.16569486],
       [0.35027008, 0.44741951, 0.53988816, ..., 1.05      , 0.66      ,
        0.24      ],
       [3.22027008, 3.31741951, 3.40988816, ..., 1.82      , 2.21      ,
        2.63      ]])

In [55]:
np.argsort(np.min(distances,axis=0))

array([12825,  9966,  9570, ..., 11124, 11103, 11104], dtype=int64)

In [82]:
X[np.argsort(np.min(distances,axis=0))][:-round(.039*len(X))]

array([3.73, 3.73, 3.73, ..., 4.47, 4.47, 4.47])

In [86]:
idx = np.argsort(np.min(distances,axis=0))
idx

array([12825,  9966,  9570, ..., 11124, 11103, 11104], dtype=int64)

In [87]:
temp = X[idx[:-round(.039*len(X))]]
temp

array([3.73, 3.73, 3.73, ..., 4.47, 4.47, 4.47])

In [94]:
labels = np.argmin(distances,axis=0)[idx[:-round(.039*len(X))]]

In [103]:
np.mean(temp[labels == 2])

3.7576338527722197

In [100]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.argmin(distances,axis=0)[:round(.039*len(X))]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [71]:
round(.039*len(X))

505

In [ ]:
np.sqrt(((X - centroid_old[0])**2))

: 

In [ ]:
labels = np.argmin(distances, axis=0)
labels

: 

In [ ]:
len(np.sqrt(((X - centroid_old[1])**2)))

: 

In [ ]:
len(X)

: 

In [ ]:
centroid_old = X[np.random.choice(range(len(X)), 4)]
distances = np.sqrt(((X - centroid_old[:, np.newaxis])**2).sum(axis=1))
distances


: 

In [ ]:
labels = np.argmin(distances, axis=0)
labels

: 

In [ ]:
X.shape

: 

: 