In [95]:
import numpy as np

import matplotlib.pyplot as plt

from random import random
from copy import deepcopy

In [96]:
X = np.reshape([random()*100 for i in range(400)],(100,4))

In [97]:
col_max = np.amax(X,axis=0)
col_min = np.amin(X,axis=0)
centroid = (col_max + col_min)/2

In [98]:
Z = (X-centroid)**2

In [99]:
alpha = (1.0 / 100) * np.ones(100)

In [100]:
ZT = Z.T
h = np.matmul(alpha,Z)
h

array([854.4840649 , 900.76170879, 786.0850101 , 701.34916922])

In [101]:
def isclose(a, b, rel_tol, abs_tol=0.0):
    return abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)

In [102]:
def calc_s(h,alpha_old,Z,u,i):
  ans=0
  for j in range(4):
            s_i_j = h[j] - alpha_old[i]*Z[i][j]
            ans += (1/(u + s_i_j/Z[i][j]))
  return ans

In [110]:
def solution(Z,alpha,h,tol):
    i = 0
    updates = 0
    converged = False
    alpha_old = np.zeros(100)
    old = 0
    start=0

    
    while i < 100:
        if converged:
            return h
        alpha_old[i] = alpha[i]
        f_x = 0
        u = random()
        f_x=calc_s(h,alpha_old,Z,u,i)
        
        if f_x == 1:
            alpha[i] = u
        
        if f_x < 1:

            alpha[i] = 0

        if f_x > 1:
            u+=0.00001*u
            while(not isclose(f_x,1,tol)):
                f_x = calc_s(h,alpha_old,Z,u,i)
                if(f_x>1):
                    u+=0.0001*u
                else:
                    u-=0.0001*u 
            alpha[i]=u    
            
                
        h = h + (alpha[i] - alpha_old[i])*Z[i]
        i += 1
        if i>=99 :
            i = 0
            updates += 1
            if old == 0:
                stored_alpha_old = deepcopy(alpha_old)
                old = 1
        if updates == 4:
            if np.all(alpha - stored_alpha_old) < tol :  #.00001
                converged = True
            else:
                updates = 0
                stored_alpha_old = deepcopy(alpha)
    

In [113]:
h = solution(Z,alpha,h,1e-05)
h

array([5578.67546033, 8129.30575987, 9758.21555533, 9263.21414035])

## weight vectors obtained are:

In [114]:
v = 1/h
v

array([0.00017925, 0.00012301, 0.00010248, 0.00010795])