In [1]:
import numpy as np

import matplotlib.pyplot as plt

from random import random
from copy import deepcopy

In [2]:
X = np.reshape([random()*100 for i in range(400)],(100,4))

In [3]:
col_max = np.amax(X,axis=0)
col_min = np.amin(X,axis=0)
centroid = (col_max + col_min)/2

In [4]:
Z = (X-centroid)**2

In [5]:
alpha = (1.0 / 100) * np.ones(100)

In [6]:
ZT = Z.T
h = np.matmul(alpha,Z)
h

array([764.17028219, 866.75344665, 841.70409949, 797.03444277])

In [13]:
def solution(Z,alpha,h):
    i = 0
    updates = 0
    converged = False
    alpha_old = np.zeros(100)
    old = 0
    while i < 100:
        if converged:
            return h
        alpha_old[i] = alpha[i]
        f_x = 0
        for j in range(4):
            s_i_j = h[j] - alpha_old[i]*Z[i][j]
            f_x += (1/(i/100 + s_i_j/Z[i][j]))
        if f_x == 1:
            alpha[i] = i/100
        else:
            alpha[i] = 0
        h = h + (alpha[i] - alpha_old[i])*Z[i]
        i += 1
        if i>99 :
            i = 0
            updates += 1
            if old == 0:
                stored_alpha_old = deepcopy(alpha_old)
                old = 1
        if updates == 4:
            if np.all(alpha - stored_alpha_old) < .00001:
                converged = True
            else:
                updates = 0
                stored_alpha_old = deepcopy(alpha)
    

In [14]:
h = solution(Z,alpha,h)
h

array([-2.50687427e+12,  2.21633840e+12,  1.70590895e+12, -1.84573755e+12])

In [9]:
v = 1/h
v

array([-2.50687427e+12,  2.21633840e+12,  1.70590895e+12, -1.84573755e+12])

In [10]:
def coordinatedescent(S,Z,i,var_x):
  sum=0
  for j in range(4):
    sum+=1/var_x[i,j]+(S[i,j]/Z[i,j])
  if(sum==1):
    return var_x[i] 


In [11]:
def getS(h,alpha,Z,n,d,i):
  S = np.reshape([random()*100 for io in range(400)],(100,4))
  for j in range(4):
    S[i,j]= h[j]-alpha[j]*Z[i,j]
  return S


In [12]:
def meepcalgo(n):
  index= np.random.randint(n)
  converged = False
  # alpha_i=X[index,:]
  while(index<100):
    if converged:
      break
    alpha_old = alpha[index]
    S = getS(h,alpha_old,Z,n,4,index)
    var_x=np.reshape([random() for i in range(100)],(100,4))
    f_val=coordinatedescent(S,Z,index)
    index+=1
    if(index==100):
      index=0