In [1]:
import sys
sys.path.append('/Users/user/meepc')
import numpy as np
import pandas as pd
from models import Hankel,Corrhankel,RobustPipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
# hankel = Hankel()
# corrhankel = Corrhankel() 
# lag = 360
# stride = 0.5


In [3]:
# def flatten_pca(list_of_lists):
#   flattened_arrays = []
#   for sublist in list_of_lists:
#     for array in sublist:
#       flattened_arrays.append(array.flatten())
#   flattened_arrays=np.unique(np.concatenate(flattened_arrays))
#   return flattened_arrays


# def flatten_meepc(list_of_lists):
#   flattened_arrays = []
#   for sublist in list_of_lists:
#     for array in sublist:
#       for element in array:
#         flattened_arrays.append(element)
#   flattened_arrays=np.unique(np.concatenate(flattened_arrays))
#   return flattened_arrays

In [4]:
# train_normal = pd.read_csv('~/data/te/normal_training.csv')
# train_attack = pd.read_csv('~/data/te/attack_training.csv')
# train_normal = pd.concat((train_normal,train_attack),axis=0,ignore_index=True)
# y_truth = train_normal.loc[:,'LABEL']

In [5]:
# sensors = [col for col in train_normal.columns if col not in ['faultNumber', 'simulationRun', 'sample','LABEL']]

In [6]:
# #attack indexes in original training data
# temp = hankel.fit(np.array(y_truth) ,lag,stride)
# attack_idx = np.any(temp>0,axis=0).astype(int)
# attack_idx = np.where(attack_idx>0)[0]
# attack_idx

In [7]:
# len(attack_idx)/len(temp)

In [8]:
# scaler = StandardScaler()
# X_normal = pd.DataFrame(index=train_normal.index, columns=sensors, data=scaler.fit_transform(train_normal[sensors]))
# X_attack = pd.DataFrame(data=scaler.fit_transform(train_attack.loc[:,sensors]),index=train_attack.index,columns=sensors).reset_index().drop(columns=['index'])

In [9]:
# corr_normal,nolag_normal = corrhankel.fit(X_normal.to_numpy(),lag,stride)

In [10]:
# corr_attack,nolag_attack = corrhankel.fit(X_attack.to_numpy(),lag,stride)

In [11]:
# df_test1 = pd.read_csv('~/data/te/normal_testing.csv')
# df_test2 = pd.read_csv('~/data/te/attack_testing.csv')
# df_test=pd.concat((df_test1,df_test2),axis=0)

In [12]:
# X_test = pd.DataFrame(index=df_test.index, columns=sensors, data=scaler.fit_transform(df_test[sensors]))
# Y_test = df_test.loc[:,'LABEL']

In [13]:
# labels = hankel.fit(np.array(Y_test),lag,stride)
# y_actual = np.any(labels>0,axis=0).astype(int)

# Multiple clusters + No threshold tuning

In [14]:
# cluster_fscore = []
# for k in range(2,5):
#     print('-------------------------------------',k,'-------------------------------------')
    
#     sensor_predicted = []
#     accuracy = []
#     precision = []
#     recall = []
#     fscore = []
#     cluster_indexes=[]
#     pca_indexes=[]
#     meepc_indexes=[]
#     pca_counts=0
#     meepc_counts=0
#     for i,sens in enumerate(sensors):
#         print(sens)
#         train_normal = X_normal.loc[:,sens].values
#         train_attack = X_attack.loc[:,sens].values
#         model = RobustPipeline()
#         model.fit(train_normal,train_attack,lag,stride,optimal_k=k,tune=False,kscore_init='inertia',alpha=0.1,y_truth=y_truth)
#         test = X_test.loc[:,sens].values
#         y_predicted = model.predict(test)
#         sensor_predicted.append(y_predicted)
#         accuracy.append(accuracy_score(y_actual,y_predicted)) 
#         precision.append(precision_score(y_actual,y_predicted))
#         recall.append(recall_score(y_actual,y_predicted))
#         fscore.append(f1_score(y_actual,y_predicted))

#         cluster_indexes.append(model.cluster_idx)
#         pca_indexes.append(model.pca_idx)
#         pca_counts=max(pca_counts,model.total_pca_attacks)
#         # meepc_counts=max(meepc_counts,model.counts_meepc)
#         meepc_indexes.append(model.total_meepc_attacks)
    
            
#     sensor_predicted = np.asarray(sensor_predicted)
#     y_predicted = np.any(sensor_predicted,axis=0).astype(int)
#     print('------Number of Clusters: ',k,'-----------') 
#     print("Accuracy ",accuracy_score(y_actual,y_predicted))
#     print("Precision ",precision_score(y_actual,y_predicted))
#     print("Recall ",recall_score(y_actual,y_predicted))
#     print("F1-score ",f1_score(y_actual,y_predicted),'\n')

#     #cluster
#     cluster_inactive_idx = np.unique(np.concatenate(cluster_indexes))
#     commonidxs=np.intersect1d(attack_idx,cluster_inactive_idx)
#     percentage = len(commonidxs)/len(attack_idx)*100
#     print("Cluster - attack points detected {} %".format(percentage))
#     #PCA
    
#     # percentage = pca_counts/len(attack_idx)*100
#     # print("PCA - attack points detected {} %".format(percentage))
#     pca_inactive_idx = flatten_pca(pca_indexes)
#     commonidxs=np.intersect1d(attack_idx,pca_inactive_idx)
#     percentage = len(commonidxs)/len(attack_idx)*100
#     print("PCA - attack points detected {} %".format(percentage))


#     #Meepc
#     # percentage = meepc_counts/len(attack_idx)*100
#     # print("Meepc - attack points detected {} %".format(percentage))
#     meepc_inactive_idx = flatten_meepc(meepc_indexes)
#     commonidxs=np.intersect1d(attack_idx,meepc_inactive_idx)
#     percentage = len(commonidxs)/len(attack_idx)*100
#     print("MEEPC - attack points detected {} %".format(percentage))
    
#     cluster_fscore.append(f1_score(y_actual,y_predicted))

In [15]:
# cluster_fscore

In [147]:
from models import Hankel
hankel = Hankel()
temp = np.random.randint(0, 2, size=100)
print(temp)
temp = hankel.fit(temp,lag=10)
zero_cols = np.random.choice(5, 4, replace=False)
for col in zero_cols:
    temp[:, col] = 0
print(temp)
y_train = np.any(temp>0,axis=0).astype(int)
temp = temp.T
temp

[1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0 1
 0 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 1 1 0
 1 0 1 0 1 1 0 0 0 1 1 1 1 0 0 1 0 1 1 1 0 0 0 1 1 0]
[[0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1]
 [0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 1]
 [0 0 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1 0]]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 1, 0]])

In [148]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [149]:
np.where(y_train>0)[0]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
      dtype=int64)

In [150]:
from models import Robustcluster
rc = Robustcluster()
centroid_new,labels,alpha_idx = rc.fit(temp,optimal_k=2,alpha_factor=0.2,Labels=y_train,max_iter=60)

------[CLUSTER] attack points found is 0 


In [151]:
centroid_new

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [152]:
labels

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1], dtype=int64)

In [153]:
alpha_idx

array([3, 2, 1, 0], dtype=int64)

In [154]:
cluster_indices = [[] for _ in range(len(labels))]
for i, assignment in enumerate(labels):
    cluster_indices[assignment].append(i)
cluster_indices

[[0, 1, 2, 3, 4, 6, 7, 10, 11, 12, 15, 16],
 [5, 8, 9, 13, 14, 17],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [155]:
from models import Rank, RobustPCA, Robustmeepc
rank = Rank()
pca = RobustPCA()
meepc = Robustmeepc()
clusterR = []
clusterV = []
for i in np.unique(labels):
    cluster_ = temp[np.where(labels == i)[0]]
    # print(cluster_)
    r = rank.fit(cluster_)
    # print(r)
    clusterR.append(r)
    VT,pca_count,pca_alpha_idx = pca.fit(cluster_,r,alpha=0.2,Labels=y_train[np.where(labels == i)[0]],cluster_index=np.asarray(cluster_indices[i]))
    V = VT.T
    clusterV.append(V)
    cluster_ = np.matmul(cluster_,V[:,:r])
    print(cluster_)
    weight,center,counts,meepc_attacks = meepc.fit(cluster_,alpha_factor=0.2,Labels=y_train[np.where(labels == i)[0]],cluster_index=np.asarray(cluster_indices[i]))
    print(weight)
    print(center)
    print(counts)
    print(meepc_attacks)
    
        

7
(10, 10)
(7,)
(7, 10)
7
(10, 10)
(7,)
(7, 10)
------[PCA] attack points found is 2 
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.77885752e+00  3.50014044e-01  1.22474487e+00  3.02627500e-01
   1.24826300e-01  3.25562698e-01 -1.21569421e-14]
 [-9.80905641e-01 -1.40651228e+00 -1.38777878e-17 -7.29226051e-01
  -7.05690128e-01  1.72563432e-01  0.00000000e+00]
 [-1.09540898e+00 -9.72484457e-02  1.12410081e-15  9.98490800e-01
  -8.18441667e-01 -3.51839819e-01  0.00000000e+00]
 [-9.66994211e-01 -6.98334793e-01  1.22474487e+00 -7.13810612e-02
   9.22466451e-03  1.37400413