In [1]:
import sys
sys.path.append("C:/Users/user/meepc")
import numpy as np
import pandas as pd
from models import Hankel,Rank,Cluster,Meepc,Pipeline
import warnings
warnings.simplefilter('ignore')
import math
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from scipy.linalg import hankel

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df_1 = pd.read_csv('~/data/ctown/dataset03.csv')
df_2 = pd.read_csv('~/data/ctown/dataset04.csv')
train_normal=pd.concat((df_1,df_2[df_2['ATT_FLAG']==0]),axis=0,ignore_index=True)
train_attack=df_2[df_2['ATT_FLAG']==1]

In [3]:
hankel = Hankel()
lag = 60
stride = 0.5

In [4]:
sensors=[col for col in train_normal.columns if col not in ['DATETIME','ATT_FLAG']]


In [5]:
scaler = StandardScaler()
X_normal=pd.DataFrame(data=scaler.fit_transform(train_normal.loc[:,sensors]),index=train_normal.index,columns=sensors)
X_normal

L_T1      L_T2      L_T3      L_T4      L_T5      L_T6      L_T7   
0     -1.810652 -0.840399 -1.489684 -1.438753 -0.125827 -0.299891 -2.102859  \
1     -1.891658 -0.867565 -0.824829 -1.366330  0.513682  0.702713 -1.754244   
2     -1.968762 -0.883198 -0.091921 -0.577770  1.123162  0.731687 -1.280055   
3     -1.958116 -0.867475  0.693507  0.327115  1.636865  0.731687 -0.127985   
4     -1.832527 -0.813155  1.524846  1.560727  1.028078  0.731687  1.359430   
...         ...       ...       ...       ...       ...       ...       ...   
12441 -0.026020 -0.622019 -0.519318 -0.979847  1.456856 -2.422136 -1.347590   
12442 -0.367893 -0.492759 -1.152625 -1.202467  1.280082 -1.971590 -1.612310   
12443 -0.643058 -0.356696 -1.844844 -2.000190 -0.066119 -1.295771 -1.732637   
12444 -0.968254 -0.519972 -1.285178 -2.853569 -1.439516 -1.521044 -2.310208   
12445 -1.318464 -0.792099 -0.696055 -1.554950 -1.589094 -1.352089 -2.550863   

          F_PU1  S_PU1     F_PU2  ...    P_J300    P_J256    P_J289    P_J415   
0     -0.192322    0.0  0.701055  ... -0.485068  0.969072 -0.467118  0.198329  \
1     -0.182644    0.0  0.703361  ... -0.486352  1.186900 -0.470150  0.423304   
2     -0.249670    0.0  0.687387  ... -0.484604  1.376971 -0.470137  0.513959   
3     -0.333661    0.0  0.667368  ... -0.451086  1.558821 -0.437744  0.705006   
4     -0.355917    0.0  0.662064  ... -0.395961  1.780926 -0.383674  1.024098   
...         ...    ...       ...  ...       ...       ...       ...       ...   
12441  1.901208    0.0 -1.641849  ... -0.123946 -1.108734 -0.143233  0.189478   
12442  1.805874    0.0 -1.641849  ... -0.018536 -1.277789 -0.040691  0.099141   
12443  1.963771    0.0 -1.641849  ... -0.360210  0.735496 -0.340993  0.014118   
12444  1.895249    0.0 -1.641849  ... -0.730962  0.796970 -0.729189  2.778709   
12445  1.926034    0.0 -1.641849  ... -0.778215  1.143355 -0.780460  3.081605   

         P_J302    P_J306    P_J307    P_J317     P_J14    P_J422  
0     -1.258253  0.754636 -1.256119 -0.150254 -1.034333 -0.359477  
1     -1.270108  0.771354 -1.267867 -0.140255 -1.042174 -0.371926  
2     -1.100738  0.955519 -1.097261  0.847781 -1.042107 -0.371820  
3      0.355822 -0.980130  0.350843  1.572762 -1.019584 -0.336060  
4      0.396924 -0.972501  0.391854  1.653455 -0.990238 -0.289469  
...         ...       ...       ...       ...       ...       ...  
12441 -1.360548  0.723200 -1.357927 -0.354694 -0.918065 -0.174880  
12442  0.213483 -1.362938  0.206009 -0.194622 -0.844885 -0.058695  
12443  0.000592 -1.492194 -0.005821 -0.347161 -0.965277 -0.249839  
12444  0.070801 -1.547303  0.064038 -0.283132 -1.130522 -0.512194  
12445 -1.426227  0.620997 -1.421025 -0.113645 -1.184816 -0.598397  

[12446 rows x 43 columns]

In [6]:
X_attack=pd.DataFrame(data=scaler.fit_transform(train_attack.loc[:,sensors]),index=train_attack.index,columns=sensors).reset_index().drop(columns=['index'])
X_attack 

L_T1      L_T2      L_T3      L_T4      L_T5      L_T6      L_T7   
0    0.510851 -0.546397 -0.878085 -2.084040 -1.526839 -2.239309 -0.533841  \
1    0.623110 -1.147382 -0.297260 -2.101038 -1.035659 -0.755638 -0.193180   
2    0.757819 -1.734552  0.341648 -1.710086 -0.312534  0.613905  0.182722   
3    0.735368 -1.858894  0.995076 -0.911185  0.451524  0.785098  0.770069   
4    0.690464 -1.617118  1.503298 -0.078287  1.270157 -0.013802  1.745065   
..        ...       ...       ...       ...       ...       ...       ...   
487 -1.824121  0.323996 -0.268218 -0.316258  1.720405  0.785098  0.558624   
488 -1.741798  0.241102  0.428772  0.431650  0.778977  0.785098  1.145971   
489 -1.622056  0.185839  1.111241  0.737612 -0.176095  0.785098  1.944763   
490 -1.427475  0.234194  1.633983  1.434527 -0.899221 -0.812702  0.417661   
491 -1.195475  0.593404  1.343571  1.196556 -1.513195 -2.353438 -0.886249   

        F_PU1  S_PU1     F_PU2  ...    P_J300    P_J256    P_J289    P_J415   
0   -0.623119    0.0  0.548804  ... -2.059407  0.794886 -2.054304  0.013617  \
1   -0.784230    0.0  0.506152  ... -2.298174  0.975545 -2.298500  0.105519   
2   -0.896547    0.0  0.476418  ... -2.578631  0.907219 -2.577037  0.232052   
3   -0.477660    0.0  0.587312  ... -0.797353  1.370448 -0.783719  0.457146   
4   -0.474898    0.0  0.587799  ... -0.069683 -0.380559 -0.089286  0.707547   
..        ...    ...       ...  ...       ...       ...       ...       ...   
487 -0.129661    0.0  0.679439  ...  0.059176  1.170102  0.082415  0.530402   
488 -0.233692    0.0  0.651898  ...  0.055386  1.181682  0.078599  0.405202   
489 -0.284327    0.0  0.638493  ...  0.062966  1.538369  0.082415  0.575687   
490 -0.369946    0.0  0.615827  ...  0.532920 -0.321497  0.517390  0.856722   
491 -0.445438    0.0  0.595842  ...  1.533467 -0.432672  1.539962 -1.793799   

       P_J302    P_J306    P_J307    P_J317     P_J14    P_J422  
0   -1.323365  0.506761 -1.344766  1.507526  0.763488 -2.086719  
1    0.590949  1.095478  0.604112 -1.873753  0.980724 -2.343036  
2    0.696182  1.172992  0.708874 -1.758276  1.095377 -2.634306  
3    0.419171  1.141594  0.433104 -1.461149 -0.877852 -0.618722  
4   -1.112899  0.855085 -1.130620  2.164060 -0.657599 -0.051718  
..        ...       ...       ...       ...       ...       ...  
487 -0.947312  0.784439 -0.944206  0.232086 -0.570101  0.173530  
488  0.106567 -1.176969  0.104953  0.627823 -0.565575  0.185181  
489  0.573926 -1.154401  0.587165 -1.086172 -0.564067  0.189065  
490  0.654398 -1.162251  0.667277 -1.221112 -0.437345  0.515286  
491  0.298462 -1.160288  0.295989  0.350158 -0.079811  1.435697  

[492 rows x 43 columns]

In [7]:
df_test = pd.read_csv('~/data/ctown/test_dataset.csv')
df_test

DATETIME  L_T1  L_T2  L_T3  L_T4  L_T5  L_T6  L_T7   F_PU1  S_PU1   
0     04/01/17 00  0.73  2.27  4.00  3.26  3.87  5.50  4.28   98.93    1.0  \
1     04/01/17 01  0.69  2.25  4.53  3.26  3.84  5.50  4.78   97.95    1.0   
2     04/01/17 02  0.90  2.31  5.03  3.41  3.32  5.16  3.22   96.82    1.0   
3     04/01/17 03  1.11  2.54  5.16  3.97  2.82  5.01  2.54   96.76    1.0   
4     04/01/17 04  1.27  2.99  4.94  4.27  2.35  5.38  3.41   94.77    1.0   
...           ...   ...   ...   ...   ...   ...   ...   ...     ...    ...   
2084  31/03/17 20  1.94  2.09  3.67  2.95  1.74  4.96  2.09  120.00    1.0   
2085  31/03/17 21  1.54  2.27  3.24  2.84  2.07  5.02  1.84  122.23    1.0   
2086  31/03/17 22  1.07  2.24  2.99  2.30  2.34  5.12  1.78  122.44    1.0   
2087  31/03/17 23  0.85  2.14  3.44  2.35  2.67  5.24  1.82   98.71    1.0   
2088  01/04/17 00  0.74  2.11  3.89  2.44  3.02  5.29  1.62   98.57    1.0   

      ...  P_J256  P_J289  P_J415  P_J302  P_J306  P_J307  P_J317  P_J14   
0     ...   90.54   26.74   84.52   19.43   83.27   19.33   71.33  29.61  \
1     ...   90.43   26.73   85.04   25.97   64.22   25.86   73.79  29.63   
2     ...   91.72   26.89   87.16   29.18   63.81   29.18   59.05  29.80   
3     ...   76.12   28.23   88.83   26.53   63.42   26.41   70.92  30.80   
4     ...   75.68   31.32   69.55   27.46   63.43   27.34   70.88  33.61   
...   ...     ...     ...     ...     ...     ...     ...     ...    ...   
2084  ...   70.07   27.15   84.05   18.28   80.39   18.17   65.97  29.66   
2085  ...   68.29   27.08   83.12   17.04   79.84   16.93   66.14  29.53   
2086  ...   87.08   26.20   83.77   16.97   80.25   16.86   66.29  28.98   
2087  ...   87.85   26.59   84.07   19.00   81.37   18.89   66.07  29.49   
2088  ...   90.58   26.60   84.79   19.29   82.56   19.18   68.10  29.48   

      P_J422  ATT_FLAG  
0      28.71       0.0  
1      28.73       0.0  
2      28.90       0.0  
3      29.90       0.0  
4      32.71       0.0  
...      ...       ...  
2084   28.76       0.0  
2085   28.63       0.0  
2086   28.08       0.0  
2087   28.59       0.0  
2088   28.58       0.0  

[2089 rows x 45 columns]

In [8]:
test_combined = pd.concat((df_test,train_attack),axis=0)
X_test = pd.DataFrame(index=test_combined.index, columns=sensors, data=scaler.fit_transform(test_combined[sensors]))
Y_test = test_combined.loc[:,'ATT_FLAG']


In [9]:
labels = hankel.fit(np.array(Y_test),lag,stride)
y_actual = np.any(labels>0,axis=0).astype(int)
y_actual

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Epasad with 1 cluster and no threshold tuning (training attack included in test data)

In [10]:
#calculating correlation matrix
from models import Corrhankel
Corrhankel=Corrhankel()
corr_matrix,no_of_lags=Corrhankel.fit(X_normal.to_numpy(),lag,stride)
corr_matrix_test,no_of_lag_test=Corrhankel.fit(X_test.to_numpy(),lag,stride)

In [11]:
sensor_models= []
sensor_predicted = []
accuracy = []
precision = []
recall = []
fscore = []
for i,sens in enumerate(sensors):
    train_normal = X_normal.loc[:,sens].values
    train_attack = X_attack.loc[:,sens].values
    model = Pipeline()
    model.fit(train_normal,train_attack,lag,stride,optimal_k=1,tune=False,kscore_init='inertia',corr_normal=corr_matrix[:,i].reshape(no_of_lags,len(X_normal.columns)).T)
    test = X_test.loc[:,sens].values
    y_predicted = model.predict(test,corr_matrix_test[:,i].reshape(no_of_lag_test,len(X_test.columns)).T)
    sensor_predicted.append(y_predicted)
    accuracy.append(accuracy_score(y_actual,y_predicted))
    precision.append(precision_score(y_actual,y_predicted))
    recall.append(recall_score(y_actual,y_predicted)) 
    fscore.append(f1_score(y_actual,y_predicted))
    sensor_models.append(model)   

In [12]:
sensor_predicitions = np.asarray(sensor_predicted)
predicted_label=np.any(sensor_predicitions>0,axis=0).astype(int)
predicted_label

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [13]:
print("Accuracy ",accuracy_score(y_actual,predicted_label))
print("Precision ",precision_score(y_actual,predicted_label))
print("Recall ",recall_score(y_actual,predicted_label))
print("F1-score ",f1_score(y_actual,predicted_label))

Accuracy  0.7764705882352941
Precision  0.7547169811320755
Recall  0.8695652173913043
F1-score  0.8080808080808081


In [14]:
# Accuracy  0.7764705882352941
# Precision  0.7547169811320755
# Recall  0.8695652173913043
# F1-score  0.8080808080808081

In [15]:
print("Accuracy -  Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(accuracy).mean(), np.median(np.asarray(accuracy)),np.asarray(accuracy).min(), np.asarray(accuracy).max()))
print("precision - Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(precision).mean(), np.median(np.asarray(precision)),np.asarray(precision).min(), np.asarray(precision).max()))
print("recall -    Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(recall).mean(), np.median(np.asarray(recall)),np.asarray(recall).min(), np.asarray(recall).max()))
print("f1 -        Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(fscore).mean(), np.median(np.asarray(fscore)),np.asarray(fscore).min(), np.asarray(fscore).max()))

Accuracy -  Mean: 0.49904240766073876 Median : 0.5058823529411764 Min : 0.4588235294117647 Max : 0.6
precision - Mean: 0.6150655223329642 Median : 0.8333333333333334 Min : 0.0 Max : 1.0
recall -    Mean: 0.0839231547017189 Median : 0.08695652173913043 Min : 0.0 Max : 0.32608695652173914
f1 -        Mean: 0.14294762840667963 Median : 0.16 Min : 0.0 Max : 0.46875000000000006


# Multiple clusters: no threshold tuning (training included in test data)

In [16]:
sensor_models= []
sensor_predicted = []
accuracy = []
precision = []
recall = []
fscore = []
for i,sens in enumerate(sensors):
    train_normal = X_normal.loc[:,sens].values
    train_attack = X_attack.loc[:,sens].values
    model = Pipeline()
    model.fit(train_normal,train_attack,lag,stride,tune=False,kscore_init='inertia',corr_normal=corr_matrix[:,i].reshape(no_of_lags,len(X_normal.columns)).T)
    test = X_test.loc[:,sens].values
    y_predicted = model.predict(test,corr_matrix_test[:,i].reshape(no_of_lag_test,len(X_test.columns)).T)
    sensor_predicted.append(y_predicted)
    accuracy.append(accuracy_score(y_actual,y_predicted))
    precision.append(precision_score(y_actual,y_predicted))
    recall.append(recall_score(y_actual,y_predicted)) 
    fscore.append(f1_score(y_actual,y_predicted))
    sensor_models.append(model)   

In [17]:
sensor_predicitions = np.asarray(sensor_predicted)
predicted_label=np.any(sensor_predicitions>0,axis=0).astype(int)
predicted_label

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
print("Accuracy ",accuracy_score(y_actual,predicted_label))
print("Precision ",precision_score(y_actual,predicted_label))
print("Recall ",recall_score(y_actual,predicted_label))
print("F1-score ",f1_score(y_actual,predicted_label))

Accuracy  0.5529411764705883
Precision  0.5487804878048781
Recall  0.9782608695652174
F1-score  0.7031250000000001


In [19]:
# Accuracy  0.5882352941176471
# Precision  0.5679012345679012
# Recall  1.0
# F1-score  0.7244094488188977

In [20]:
print("Accuracy -  Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(accuracy).mean(), np.median(np.asarray(accuracy)),np.asarray(accuracy).min(), np.asarray(accuracy).max()))
print("precision - Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(precision).mean(), np.median(np.asarray(precision)),np.asarray(precision).min(), np.asarray(precision).max()))
print("recall -    Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(recall).mean(), np.median(np.asarray(recall)),np.asarray(recall).min(), np.asarray(recall).max()))
print("f1 -        Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(fscore).mean(), np.median(np.asarray(fscore)),np.asarray(fscore).min(), np.asarray(fscore).max()))

Accuracy -  Mean: 0.5102599179206566 Median : 0.5058823529411764 Min : 0.43529411764705883 Max : 0.6235294117647059
precision - Mean: 0.5496850674979598 Median : 0.6923076923076923 Min : 0.0 Max : 1.0
recall -    Mean: 0.16279069767441862 Median : 0.1956521739130435 Min : 0.0 Max : 0.41304347826086957
f1 -        Mean: 0.23814671985631844 Median : 0.2903225806451613 Min : 0.0 Max : 0.5428571428571429


# Epasad with 1 cluster : (training attack is not in test data)

In [21]:
X_test = pd.DataFrame(index=df_test.index, columns=sensors, data=scaler.fit_transform(df_test[sensors]))
Y_test = df_test.loc[:,'ATT_FLAG']

In [22]:
corr_matrix_test,no_of_lag_test=Corrhankel.fit(X_test.to_numpy(),lag,stride)
corr_matrix_attack,no_of_lag_attack=Corrhankel.fit(X_attack.to_numpy(),lag,stride)

In [23]:
labels = hankel.fit(np.array(Y_test),lag,stride)
y_actual = np.any(labels>0,axis=0).astype(int)

In [24]:
sensor_models= []
sensor_predicted = []
accuracy = []
precision = []
recall = []
fscore = []
for i,sens in enumerate(sensors):
    train_normal = X_normal.loc[:,sens].values
    train_attack = X_attack.loc[:,sens].values
    model = Pipeline()
    model.fit(train_normal,train_attack,lag,stride,optimal_k=1,tune=False,kscore_init='inertia',corr_normal=corr_matrix[:,i].reshape(no_of_lags,len(X_normal.columns)).T,corr_attack=corr_matrix_attack[:,i].reshape(no_of_lag_attack,len(X_attack.columns)).T)
    test = X_test.loc[:,sens].values
    y_predicted = model.predict(test,corr_matrix_test[:,i].reshape(no_of_lag_test,len(X_test.columns)).T)
    sensor_predicted.append(y_predicted)
    accuracy.append(accuracy_score(y_actual,y_predicted))
    precision.append(precision_score(y_actual,y_predicted))
    recall.append(recall_score(y_actual,y_predicted)) 
    fscore.append(f1_score(y_actual,y_predicted))
    sensor_models.append(model)   

In [25]:
sensor_predicitions = np.asarray(sensor_predicted)
predicted_label=np.any(sensor_predicitions>0,axis=0).astype(int)
predicted_label

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0])

In [26]:
print("Accuracy ",accuracy_score(y_actual,predicted_label))
print("Precision ",precision_score(y_actual,predicted_label))
print("Recall ",recall_score(y_actual,predicted_label))
print("F1-score ",f1_score(y_actual,predicted_label))

Accuracy  0.6764705882352942
Precision  0.5897435897435898
Recall  0.7931034482758621
F1-score  0.676470588235294


In [27]:
# Accuracy  0.6764705882352942
# Precision  0.5853658536585366
# Recall  0.8275862068965517
# F1-score  0.6857142857142856

In [28]:
print("Accuracy -  Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(accuracy).mean(), np.median(np.asarray(accuracy)),np.asarray(accuracy).min(), np.asarray(accuracy).max()))
print("precision - Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(precision).mean(), np.median(np.asarray(precision)),np.asarray(precision).min(), np.asarray(precision).max()))
print("recall -    Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(recall).mean(), np.median(np.asarray(recall)),np.asarray(recall).min(), np.asarray(recall).max()))
print("f1 -        Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(fscore).mean(), np.median(np.asarray(fscore)),np.asarray(fscore).min(), np.asarray(fscore).max()))

Accuracy -  Mean: 0.5896032831737344 Median : 0.5735294117647058 Min : 0.5588235294117647 Max : 0.6470588235294118
precision - Mean: 0.4538859073742795 Median : 0.5 Min : 0.0 Max : 1.0
recall -    Mean: 0.06415396952686447 Median : 0.034482758620689655 Min : 0.0 Max : 0.20689655172413793
f1 -        Mean: 0.107771444978657 Median : 0.06666666666666667 Min : 0.0 Max : 0.31578947368421056


# Multiple clusters : No threshold tuning (training attack is not in test data)

In [29]:
sensor_models= []
sensor_predicted = []
accuracy = []
precision = []
recall = []
fscore = []
for i,sens in enumerate(sensors):
    train_normal = X_normal.loc[:,sens].values
    train_attack = X_attack.loc[:,sens].values
    model = Pipeline()
    model.fit(train_normal,train_attack,lag,stride,tune=False,kscore_init='inertia',corr_normal=corr_matrix[:,i].reshape(no_of_lags,len(X_normal.columns)).T,corr_attack=corr_matrix_attack[:,i].reshape(no_of_lag_attack,len(X_attack.columns)).T)
    test = X_test.loc[:,sens].values
    y_predicted = model.predict(test,corr_matrix_test[:,i].reshape(no_of_lag_test,len(X_test.columns)).T)
    sensor_predicted.append(y_predicted)
    accuracy.append(accuracy_score(y_actual,y_predicted))
    precision.append(precision_score(y_actual,y_predicted))
    recall.append(recall_score(y_actual,y_predicted)) 
    fscore.append(f1_score(y_actual,y_predicted))
    sensor_models.append(model)   

In [30]:
sensor_predicitions = np.asarray(sensor_predicted)
predicted_label=np.any(sensor_predicitions>0,axis=0).astype(int)
predicted_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1])

In [31]:
print("Accuracy ",accuracy_score(y_actual,predicted_label))
print("Precision ",precision_score(y_actual,predicted_label))
print("Recall ",recall_score(y_actual,predicted_label))
print("F1-score ",f1_score(y_actual,predicted_label))

Accuracy  0.4411764705882353
Precision  0.4307692307692308
Recall  0.9655172413793104
F1-score  0.5957446808510639


In [32]:
# Accuracy  0.45588235294117646
# Precision  0.4393939393939394
# Recall  1.0
# F1-score  0.6105263157894737

In [33]:
print("Accuracy -  Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(accuracy).mean(), np.median(np.asarray(accuracy)),np.asarray(accuracy).min(), np.asarray(accuracy).max()))
print("precision - Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(precision).mean(), np.median(np.asarray(precision)),np.asarray(precision).min(), np.asarray(precision).max()))
print("recall -    Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(recall).mean(), np.median(np.asarray(recall)),np.asarray(recall).min(), np.asarray(recall).max()))
print("f1 -        Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(fscore).mean(), np.median(np.asarray(fscore)),np.asarray(fscore).min(), np.asarray(fscore).max()))

Accuracy -  Mean: 0.5742134062927496 Median : 0.5735294117647058 Min : 0.47058823529411764 Max : 0.6617647058823529
precision - Mean: 0.37765212823352357 Median : 0.42857142857142855 Min : 0.0 Max : 1.0
recall -    Mean: 0.11948676824378507 Median : 0.10344827586206896 Min : 0.0 Max : 0.3448275862068966
f1 -        Mean: 0.17180477619338905 Median : 0.14634146341463414 Min : 0.0 Max : 0.4444444444444445


# Multiple clusters : threshold tuning (training attack is not in test data)

In [34]:
sensor_models= []
sensor_predicted = []
accuracy = []
precision = []
recall = []
fscore = []
for i,sens in enumerate(sensors):
    train_normal = X_normal.loc[:,sens].values
    train_attack = X_attack.loc[:,sens].values
    model = Pipeline()
    model.fit(train_normal,train_attack,lag,stride,tune=True,kscore_init='inertia',corr_normal=corr_matrix[:,i].reshape(no_of_lags,len(X_normal.columns)).T,corr_attack=corr_matrix_attack[:,i].reshape(no_of_lag_attack,len(X_attack.columns)).T)
    test = X_test.loc[:,sens].values
    y_predicted = model.predict(test,corr_matrix_test[:,i].reshape(no_of_lag_test,len(X_test.columns)).T)
    sensor_predicted.append(y_predicted)
    accuracy.append(accuracy_score(y_actual,y_predicted))
    precision.append(precision_score(y_actual,y_predicted))
    recall.append(recall_score(y_actual,y_predicted)) 
    fscore.append(f1_score(y_actual,y_predicted))
    sensor_models.append(model)   

In [35]:
sensor_predicitions = np.asarray(sensor_predicted)
predicted_label=np.any(sensor_predicitions>0,axis=0).astype(int)
predicted_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [36]:
print("Accuracy ",accuracy_score(y_actual,predicted_label))
print("Precision ",precision_score(y_actual,predicted_label))
print("Recall ",recall_score(y_actual,predicted_label))
print("F1-score ",f1_score(y_actual,predicted_label))

Accuracy  0.4264705882352941
Precision  0.4264705882352941
Recall  1.0
F1-score  0.5979381443298969


In [37]:
# Accuracy  0.45588235294117646
# Precision  0.4393939393939394
# Recall  1.0
# F1-score  0.6105263157894737

In [38]:
print("Accuracy -  Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(accuracy).mean(), np.median(np.asarray(accuracy)),np.asarray(accuracy).min(), np.asarray(accuracy).max()))
print("precision - Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(precision).mean(), np.median(np.asarray(precision)),np.asarray(precision).min(), np.asarray(precision).max()))
print("recall -    Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(recall).mean(), np.median(np.asarray(recall)),np.asarray(recall).min(), np.asarray(recall).max()))
print("f1 -        Mean: {} Median : {} Min : {} Max : {}".format(np.asarray(fscore).mean(), np.median(np.asarray(fscore)),np.asarray(fscore).min(), np.asarray(fscore).max()))

Accuracy -  Mean: 0.5745554035567716 Median : 0.5735294117647058 Min : 0.47058823529411764 Max : 0.6764705882352942
precision - Mean: 0.36158589472542957 Median : 0.42857142857142855 Min : 0.0 Max : 1.0
recall -    Mean: 0.1194867682437851 Median : 0.10344827586206896 Min : 0.0 Max : 0.3103448275862069
f1 -        Mean: 0.17428759037611172 Median : 0.17647058823529413 Min : 0.0 Max : 0.4285714285714286
